version: '3'
services:
  app1:
    build: ./app1
    volumes:
    # Неверный путь монтирования
      - ./storage:/app/templates:ro

  app2:
    build: ./app2
    volumes:
    # Неверный путь монтирования
      - ./storage:/app/templates:ro

  nginx:
    build: ./nginx
    ports:
    # Неверный порт для https
    - "443:443"
    depends_on:
      - app1
      - app2
